name: "Test"

on:
  workflow_call:
  pull_request:

jobs:
  test:
    name: "Cargo test"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          override: true

      - name: "Check"
        run: cargo check

      - name: "Clippy"
        run: cargo clippy

      - name: "Fmt"
        run: cargo fmt

      - name: "Test"
        run: cargo test --all-features
