name: "Test"

on:
  workflow_call:
  pull_request:

jobs:
  test:
    name: "Cargo test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true
      - run: cargo check
      - run: cargo clippy
      - run: cargo fmt
      - run: cargo test --all-features
